general:
  debug: 0

matrix:
  host: "https://springrts.com"
  domain: "springrts.com"
  username: ""
  pwd: ""

lobby:
  host: "lobby.springrts.com"
  port: 8200
  username: ""
  pwd: ""

rooms:
  "test": "#test:springrts.com"
